import java.sql.DriverManager;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.sql.DriverManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sudarshan singh
 */
public class client3 extends javax.swing.JFrame implements Runnable {
    
	    BufferedWriter bw;
	    BufferedReader br;

    /**
     * Creates new form client
     */
    public client3() {
        initComponents();
        try
	    {
	    Socket s = new Socket("192.168.43.152",3005);
	    br= new BufferedReader(new InputStreamReader(s.getInputStream()));
	    bw =new BufferedWriter(new OutputStreamWriter(s.getOutputStream()));
	    }
	    catch(Exception e)
	    {
	    	System.out.println(e);
	    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        s1 = new javax.swing.JTextArea();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        em = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        s1.setEditable(false);
        s1.setColumns(20);
        s1.setFont(s1.getFont().deriveFont((float)40));
        s1.setRows(5);
        jScrollPane1.setViewportView(s1);
        

        t1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
         
        jButton1.setText("send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("SUDARSHAN SINGH");

        em.setFont(em.getFont().deriveFont(em.getFont().getSize()+14f));
        em.setForeground(new java.awt.Color(255, 255, 0));
        em.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "😀 ", "😁", "😂", "🤣", "😃 ", "😄", "😅", "😆", "😉", "😊 ", "😋 ", "😎", " 😍 ", "😘 ", " 😗 ", "😙", " 😚", " ☺", " 🙂 ", "🤗 ", "🤔", "  😐", " 😑 ", "😶", " 🙄 ", "😏", " 😣", " 😥", " 😮", " 🤐", " 😯", " 😪", " 😫", " 😴", " 😌", " 😛", " 😜", " 😝", " 🤤", " 😒", " 😓", " 😔", " 😕", " 🙃", " 🤑", " 😲", " ☹", " 🙁", " 😖", " 😞", " 😟", " 😤", " 😢", " 😭", " 😦 ", "😧", " 😨", " 😩", "  😰", " 😱", "  😳", "  😵", "  😠", "  😷", " 🤒", " 🤕", " 🤢", "  🤧", " 😇 ", "🤠 ", "🤡 ", "🤥", "  🤓", " 😈", " 👿", " 👹", " 👺", " 💀", " 👻", " 👽", " 🤖", " 💩", " 😺", " 😸", " 😹", " 😻", " 😼", " 😽", " 🙀", " 😿", " 😾" }));
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(t1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(em))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                          

  
    
    public void run(){
   	 try
        {
        String msgin="";
        
         while((msgin=br.readLine()) !=null){
       	  s1.append(msgin+"\n");
            
           
            
        }
        }
        catch(Exception e)
        {
        	System.out.println(e);
        }
   	
   	
   }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
    	
    	
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(client3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(client3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(client3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(client3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
        
        client3 client=new client3();
        client.setVisible(true);
    	Thread t=new Thread(client);
    	t.start();
    
}
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    // TODO add your handling code here:
    try
    {
    	
    String e=em.getSelectedItem().toString();
    String msg="Sudarshan: "+t1.getText()+e;
    bw.write(msg);
    bw.write("\r\n");
    bw.flush();
    Class.forName("com.mysql.jdbc.Driver");  // loading driver  or class 
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/chat","root","");  // connection

       
       
        PreparedStatement ps = (PreparedStatement) con.prepareStatement("insert into client3 values('Sudarshan',?)");
        
        ps.setString(1,msg);
        
        
        int n = ps.executeUpdate();
      
    	   System.out.println(n+" row inserted");
     
    }
    catch(Exception e)
    {
    	System.out.println(e);
    }
    t1.setText("");
}    


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea s1;
    private javax.swing.JTextField t1;
    private javax.swing.JComboBox<String> em;
    // End of variables declaration                   
}
